import {
  Bot,
  Building2,
  ClipboardList,
  Compass,
  Contact,
  Cpu,
  Gauge,
  KanbanSquare,
  Map,
  Network,
  Plug,
  Radar,
  Target,
  TrendingUp,
  BookOpen,
  Briefcase,
  CheckSquare,
  FileCode2,
  FlaskConical,
  Home,
  Layers,
  Orbit,
  Scale,
  ScrollText,
  Search,
  ShieldCheck,
  Sparkles,
  Users,
  Workflow,
  type LucideIcon,
} from "lucide-react";

const ICONS: Record<string, LucideIcon> = {
  home: Home,
  sparkles: Sparkles,
  search: Search,
  users: Users,
  book: BookOpen,
  "file-code": FileCode2,
  flask: FlaskConical,
  orbit: Orbit,
  layers: Layers,
  briefcase: Briefcase,
  scale: Scale,
  bot: Bot,
  workflow: Workflow,
  "check-square": CheckSquare,
  shield: ShieldCheck,
  scroll: ScrollText,
  gauge: Gauge,
  trending: TrendingUp,
  map: Map,
  compass: Compass,
  clipboard: ClipboardList,
  cpu: Cpu,
  network: Network,
  kanban: KanbanSquare,
  building: Building2,
  contact: Contact,
  target: Target,
  radar: Radar,
  plug: Plug,
};

export function Icon({ name, size = 16 }: { name: string; size?: number }) {
  const Component = ICONS[name] ?? Layers;
  return <Component size={size} aria-hidden="true" />;
}
